### ISSUE TITLE
tiling window/folder manager (= "folder editor/tool") concept & design -- 2 --

### ISSUE THREAD

**Issue by mimi-uxui-dev** [wizardamigos/wizardamigos.github.io#101]
# `@Todo`
`@input` [tiling window/folder manager (= "folder editor/tool") concept & design **ISSUE**](https://github.com/wizardamigos/wizardamigos.github.io/issues/59#issue-1172449626)
- [ ] **Brainstorm**
- [ ] **Wireframes**
- [ ] 
- [ ] **Sub Components**
   - [ ] #69
   * [ ] #90 
   * [ ] #54
   * [ ] #57 
   * [ ] #96 
- [ ] Create slides, wireframes and markdown files
   * `@output` :factory: `twm editor slides`
      * next #87
  * `@output` :factory: `twm editor linked markdown file per slide in "./slides/<slidename>.md"`
     * next #87
  * `@output` :factory: `twm editor wireframes`
    * next #87

**Comment by mimi-uxui-dev** [comment]
[**Worklog A `25.05.2022`** ](https://youtu.be/PyTg_zoIjRQ)
[**Worklog B `25.05.2022`** ](https://youtu.be/8FeGR1tYA14)

**Comment by serapath** [comment]
**feedback `2-22.06.03`**

> [**Worklog A `25.05.2022`** ](https://youtu.be/PyTg_zoIjRQ)

**1. wireframing feedback**
* :heart: for the file explorer tile :100: 
* :heart: for the file explorer tile in folder icon mode :100:  - awesome idea, thank you.
  * to be honest, i think that should maybe be the default mode :slightly_smiling_face: 
* :heart: love the notifications terminal, but noticed you made it full with **for real** :smile: 
  * i imagined it to be full width in context of a specific tile :P
  * also in the "overlay version" i imagined it to be `full width`/`full height` overlay, which you showed and is super awesome
      *  (including the scroll bar and the little (x) to close it)
  * the other version was meant to overlay the tiles in the background, but not full height, so only overlay some, maybe resizable
    * ...its anyway more or less experimenting, but to me i think you got it right, i think the way you made it is cool for now :-)
    * :100: :+1:  for opening the notification terminal in a standalone tile, i think that should totally be an additional option !!! :star_struck: 
* [feedback video - vscode inspiration](https://share.vidyard.com/watch/TmTGvkNqN4EXJNotkQf43N?)
* [feedback video2 - devtools inspiration](https://share.vidyard.com/watch/BSueQ9QsftoGrq4LxcqXXT?)
* also that you thought about keyboard navigation too - thats cool.
* the next thing i noticed is, that the **command prompt** (e.g. `username/workshops/workshop-title-XYZ`) is the same as in the search bar (which you noticed too) **AND** the searchbar has the "action button" (e.g. `new`, etc...) to trigger actions, just like we could trigger actions by probably typing the command in the terminal ...which tells me, the search bar with the action button and the terminal command line are the same thing so we should merge them.
    * **maybe:** when the notifications terminal is open, the search bar could be used as the "command line"?

**regarding styling and features for the next iteration:**
1. Could we try styling/theme of the terminal to look a little bit more like the notification sidebar you made before?
2. maybe you can that sidebar and "change log" entries and just move it into the position where the terminal is shown?
3. ...oh also - i think we still need some sort of bar or UX for filtering to only show
    * chat message (e.g. hey mimi, whats up?)
    * updates
    * ...

---

**2. issue structure feedback**
i love the new TWM issue. i fixed some things about linking to the figma files.
Also the "tags" or "flags" you are talking about ...there is only `@input` and `@output` and nothing else.
I think we should not use @result anymore ...every task is either textual or an issue link and can have textual sub tasks or sub issue and each of them can have `@input` and/or `@output` links and thats it. There is nothing else.

**regarding the new TWM issue**
now the previous issue should not be linked as an `@input`, because issues itself should never be `@input` or `@output`, but instead we take specific resources/links/files/etc... that were `@output` on the old issue and use them as `@input` in the new issue and additionally use the **from** field in that input to link to the old issue where they were created.

check the todo list above - i updated the WF figma links to reflect that :slightly_smiling_face: 
* i changed the linked figma wireframes into task `@input`s coming **from** the old TWM issue where they were created and added planned `@output`s.

**another example formatted in markdown:**
```
* [ ] some new task on the new TWM issue
  * `@input` :package: [`WF 13: iteratin1`](https://figma.com/link/to/wireframe/...) from #101
  * `@input` :package: [`WF 05: iteratin 04`](https://figma.com/link/to/wireframe/...) from #101
  * [ ] do this
  * [ ] do that
  * [ ] do some more to produce the final output for the parent bullet point "some new task on the new TWM issue"
  * `@output` :question: [WF 15: TWM specs in WF - Iteration 3-](https://figma.com/link/to/wireframe/...)
* [ ] next task
```

**so you see, the above example has:**
1. a new task to do something
2. it includes two sub bullet points of already made wireframes :package: as input from issue 101 (=the old TWM issue)
3. it includes 3 textual sub tasks
4. and it has a last bullet point as planned output :question:to make the next wireframe iteration

Ideally we remove the `@input` link to the old issue completely and instead add all the `@output` figma and other links as `@input` to specific tasks in the new issue instead. Because those `@input` links will have a **from** we will know that they came from the old TWM issue  :slight_smile:


**the new TWM issue can be put as a new task into the issue where the old TWM issue is currently linked, which is our main `UI/UX/concept design` issue task:**
* https://github.com/wizardamigos/wizardamigos.github.io/issues/39




> [**Worklog B `25.05.2022`** ](https://youtu.be/8FeGR1tYA14)

:+1:
