### ISSUE TITLE
project brief @Vancouver1thedreamer

### ISSUE THREAD

**Issue by serapath** [wizardamigos/wizardamigos.github.io#104]
## `@todo`
* [ ] get familiar with how we plan and work
  * `@output` :question: `short summary video or document about how we work`
* [ ] get familiar with wizardamigos
  * `@output` :question: `short summary video or document about wizardamigos`
* [ ] get familiar with the current project plan
  * `@output` :question: `short summary video or document about the current project plan`
* [ ] get familiar with the tiling window manager issue
  * `@output` :question: `short summary about the tiling window manager`
    
---

## `@info`
1. **how we work** https://pastebin.com/mcX2yGAr (including checklist document to not forget any of the described steps)
2. **how we work screencast** https://share.vidyard.com/watch/VyP31RNEd28pAqwSDiPg1u?
3. **what is wizardamigos** https://share.vidyard.com/watch/gXwRLhvMAiWt2pVU1tXAR5?
4. **the current project plan** https://github.com/wizardamigos/wizardamigos.github.io/issues/38

**Comment by Vancouver1thedreamer** [comment]
Hello, So yesterday I took my time to go over your brainstorm session/ product definition stage for work-space screens (TMW) - you had with @mimi-uxui-dev. and so today I created a personal site map to better understand the screen layouts, and how they are to interact with one another, keeping in mind the user cases and possible scenarios that may come up when the users are on the interface, working on a task.

Although it is not perfect, I used it as a guide to help me better understand the product and how to go about the wireframes. 

I did a little pen and paper sketchings as well before creating the first iterations of wireframes. Like I said it's not perfect, still needs a lot of workings and futher research implementation

[https://www.figma.com/file/Fyzg4Bk6pOJjx3PsbVfk8t/wizard?node-id=0%3A1](figma)

**Comment by Vancouver1thedreamer** [comment]
[Worklog 1](https://share.vidyard.com/watch/GKbZ7SjsR28HohuNo4mmAc?) `21/06/2022` - `5.9min`

- [ ] make tiling window/folder manager (= "folder editor/tool") wireframes 🏭 `output` [first iteration of wireframe](https://www.figma.com/file/Fyzg4Bk6pOJjx3PsbVfk8t/wizard?node-id=0%3A1)

- Total work time spend today `5hr.9min`
