### ISSUE TITLE
project brief @KaylaOlu

### ISSUE THREAD

**Issue by serapath** [wizardamigos/wizardamigos.github.io#105]
## `@todo`
* [x] get familiar with how we plan and work
  * `@output` 📦 [Wizard Amigos .pdf](https://github.com/wizardamigos/wizardamigos.github.io/files/8991693/Wizard.Amigos.pdf)  from [comment](https://github.com/wizardamigos/wizardamigos.github.io/issues/105#issuecomment-1165201424) 
* [x] get familiar with wizardamigos
  * `@output` 📦 [Wizard Amigos .pdf](https://github.com/wizardamigos/wizardamigos.github.io/files/8991693/Wizard.Amigos.pdf)  from [comment](https://github.com/wizardamigos/wizardamigos.github.io/issues/105#issuecomment-1165201424) 
* [x] get familiar with the current project plan
  * `@output` 📦 [Project Plan Summary .pdf](https://github.com/wizardamigos/wizardamigos.github.io/files/8992670/Project.Plan.Summary.pdf)  from [comment](https://github.com/wizardamigos/wizardamigos.github.io/issues/105#issuecomment-1167373885)
* [x] lets find and choose a first good task to get started
  * `@output` 📦 [`figma wireframe1`](https://www.figma.com/file/Mk0PswDjxhhHqFvInmXbJw/Untitled?node-id=0%3A1) from [comment](https://github.com/wizardamigos/wizardamigos.github.io/issues/105#issuecomment-1170610674)
    * next #88

---

## `@info`
1. **how we work** https://pastebin.com/mcX2yGAr (including checklist document to not forget any of the described steps)
2. **how we work screencast** https://share.vidyard.com/watch/VyP31RNEd28pAqwSDiPg1u?
3. **what is wizardamigos** https://share.vidyard.com/watch/gXwRLhvMAiWt2pVU1tXAR5?
4. **the current project plan** https://github.com/wizardamigos/wizardamigos.github.io/issues/38
   * especially check this sub task https://github.com/wizardamigos/wizardamigos.github.io/issues/39#issuecomment-1060056445, where i think good first tasks could be
      1. i think `codecamp task`
      2. or maybe the `chapter task`

**Comment by KaylaOlu** [comment]
worklog 1 [https://youtu.be/kPgVrvC1LA0](url)
worklog 2 [https://youtu.be/WoDI0BEz_bs](url)

**Comment by serapath** [comment]
**feedback `2022.06.25`**

> worklog 1 [https://youtu.be/kPgVrvC1LA0](url)

here is my feedback. i was hoping for some sort of summary document too - like your notes that you mention.

But for `worklog video 1` the way you summarised it is quite good. thank you.
Maybe you could take the pastebin and bookmark the `checklist link`, because it can help every time you work to not forget a step, but otherwise it is a good summary.
If you have an output document (maybe some notes file you can link to) you could practice to edit your worklog and maybe the top level todo comment and update it accordingly ....it would include turning the :question: into a :package: when linking your output. ...and you would also type `from [comment](...link to your worklog comment...)` in markdown so the top level todo comment with your output file has a link that when clicked jumps down to your worklog comment where you introduced your output summary notes :-)

**Comment by serapath** [comment]
> **feedback `2022.06.25`**
> 
> worklog 2 [https://youtu.be/WoDI0BEz_bs](url)

good summary in the video.
i can provide you all the files and links and more to all the things mentioned in the video too if we need them.

I think the next task after we linked the outputs from the previous one so we can mark those todos as done, would be the task number 4 ...where you need to explore the current project structure - you can check what others did in their project brief and then probably come to the UI/UX issue and there is a list of many things.

If anything sticks out for you or you have questions, let me know in your worklog video.
We can together find a good first task you could start wireframing and working on and that finishes this task and we go to the next :-)

**Comment by KaylaOlu** [comment]
worklog 3 `2022. 06. 27`
`@output`  
[Project Plan Summary .pdf](https://github.com/wizardamigos/wizardamigos.github.io/files/8992516/Project.Plan.Summary.pdf)

**Comment by KaylaOlu** [comment]
worklog 4` 2022. 06. 29`
`@output `

**Comment by serapath** [comment]
**feedback `2022.07.04`**

thx, but could you fix the worklog comments above?
The youtube videos are not linked, so they should look like this:

```
[**worklog 4` 2022. 06. 29`**](https://www.youtube.com/watch?v=W-6z48tjSLk)

* `done` lets find and choose a first good task to get started - `2.46hours`
  `@output` [`figma wirefram 1`](https://www.figma.com/file/Mk0PswDjxhhHqFvInmXbJw/Untitled?node-id=0%3A1)
```
...and similar for worklog 3 if you could please update both? :-)

* and afterwards lets continue in your real codecamp issue https://github.com/wizardamigos/wizardamigos.github.io/issues/88

---
> worklog 3 `2022. 06. 27` `@output` [Project Plan Summary .pdf](https://github.com/wizardamigos/wizardamigos.github.io/files/8992516/Project.Plan.Summary.pdf)

To answer the questions about codecamps:
1. a codecamp is usually a small digital curriculum of workshops a user can do from home
2. the user learns through the curriculum of workshops listed in the codecamp website
3. each workshop can have gigs listed, but the codecamp itself has no gigs
4. a codecamp has a `theme`, `title`, `description`, `logo/icon` and `community chat`
5. sometimes codecamps can be digital or in-person events
  * so instead of "gigs" like they are listed/attached next to workshops
  * a codecamp can have a list of "events" attached to it and people can apply and get notified about it

---

> worklog 4` 2022. 06. 29` `@output ` [https://www.figma.com/file/Mk0PswDjxhhHqFvInmXbJw/Untitled?node-id=0%3A1](url)

![wireframe](https://imgur.com/GCkbIAl.png)
1. the events list:
   * :+1: for browser notifications for events
   * :+1: for a little list for events on the side to show whats upcoming :-)
2. the courses section
   * :-1: its not bad to have a wall/grid of cards, but if you search on google for "game skilltree" or check this for example http://www.dungeonsanddevelopers.com/ it would be much better so people can see how lessons depend on each other and if it is a lot of them so they don't fit on one screen, maybe a user needs to scroll or something like that?
   * :+1: for idea of calendar, but that is a different "VIEW" :-)
      * in fact @Helenphina is working on a calendar view that includes events and we might re-use this here, so you could toggle/switch between showing things like a calendar or showing them like a list with one upcoming event after the other and reminders are again just notifications
3. the codecamp menu shows `curriculum`, `events/schedule`, `chats` and `notes`
   * :+1: for curriculum, which is `courses`, so we should stick to one word and it is always shown
   * :+1: for chats but there is only a single chat per codecamp and it should be visible in the page, maybe where the events list is shown right now? ...and then the events list could move to where the codecamp menu is right now and then we get rid of the codecamp menu?
   * :-1: for notes, i think we should not have notes for now
   * :+1: for events and schedule, but it should be merged into one and a button can toggle between the calendar and the list view
   
So thats all feedback i have for now.
One thing - the "title bar" (with the notifications button) would make more sense to be on the bottom instead of top of the page - just because all the other components and pages we are building do it this way, so i would love to try how that could work :-)

For skill tree inspiration see:
1. https://hackmd.io/@mimiuxui/SkKkwDYg9
2. http://www.dungeonsanddevelopers.com/
3. [google search](https://www.google.com/search?q=skilltree&newwindow=1&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjGn6aG3d_4AhUQUsAKHSe6BJEQ_AUoAXoECAEQAw&biw=1097&bih=1152&dpr=1.75)
4. https://www.ign.com/wikis/assassins-creed-valhalla/Skill_Tree_-_List_of_Major_Skills
5. https://cdn.akamai.steamstatic.com/steamcommunity/public/images/clans/28269558/98b51b813686608aa93e5a3b99653da0d13b8192.jpg
6. https://cdn.segmentnext.com/wp-content/uploads/2020/02/wolcen-skill-tree-e1582204645745.jpg
7. https://gamedev.stackexchange.com/questions/184933/shifting-skill-tree
8. https://www.artstation.com/artwork/8wwXlx
