### ISSUE TITLE
Design TWM - Tab Component

### ISSUE THREAD

**Issue by Mehrabbruno** [wizardamigos/wizardamigos.github.io#112]
## `@todo`

https://github.com/wizardamigos/wizardamigos.github.io/issues/111

  - [x] Design - Tab components
    - `@input` 📦 [WF 14: TWM specs in WF -Iteration 2- figma file`](https://www.figma.com/file/lk41O0wlkMEdPiCBGVMOO8/?node-id=897%3A11280) from #101 
    - `@input` :package: [`twm ui/ux specification`](https://hackmd.io/yrqMJjhaQm2b8MhS4Gqxhg?view) from #111 

    - 
     - [ ] Tab Component (contains)
        - [ ] Tab Name (title of the name)
        - [ ] Switch Program/Application CTA (program icon when clicked opens a pop-over)
           - [ ] Program Icon
           - [ ] Program pop-over
              - [ ] Pop-over Title
              - [ ] Pop-over Close button
              - [ ] Program container (divs which carries each Program information)
                 - [ ] Program name
                 - [ ] Program logo
                 - [ ] Program description
              - [ ] Active state (when a program is already running it should be blue)
              - [ ] Hover state (when a program is hovered it shows a gray background)
              - [ ] Search input
    - `@output` 🏭 [`TWM iteration 15 Figma File`](https://www.figma.com/file/PiQmPX3q1V2Ph7hARR2jOm/tiling-window-manager-3?node-id=0%3A1) from [`comment`](https://github.com/wizardamigos/wizardamigos.github.io/issues/111#issuecomment-1207299400)

## `@info`

for [`TWM iteration 15 Figma File`](https://www.figma.com/file/PiQmPX3q1V2Ph7hARR2jOm/tiling-window-manager-3?node-id=0%3A1) we need to design the tab component tasks. These will be integrated into the main design file.

**Comment by Mehrabbruno** [comment]
* `done` Tab Component (contains)
   * `done` #119 
   * `done` Tab Name
   * `done` #120 
   * `done` Next and Prev buttons to toggle between directory files
   * `done` #116 
   * `done` #117 
   * `done` #118 
   * `done` Close button (to close the tab 
      * `@output` 📦 [`tab_v0.0.1`](https://www.figma.com/file/PiQmPX3q1V2Ph7hARR2jOm/tiling-window-manager-3?node-id=318%3A2706)
   * `done` Record an explanatory video for Tab Component
      * `@output` 📦 [`video recording`](https://youtu.be/EgswEKU2gUM)

**Comment by serapath** [comment]
**feedback `2022.10.14`**

the worklog is missing the link to the worklog video, could you edit it and add that?
i agree though that you could add a generic task for the project management overhead to book time on, which brings me to the missing times behind each of those tasks that should be added too :-) otherwise, great explanation.

One thing that i believe needs to change is the icon for the actions.
The vertical ". . ." menu doesn't work well with the ". . ." to show the tabs not visible because of screen widht limit. They look the same and i don't expect actions when i see ". . ." but then sometimes more tabs when i click ". . .".

Could we try to make another version with a different action `execute icon`?
maybe something like
![action icon](https://as2.ftcdn.net/v2/jpg/02/00/81/01/1000_F_200810147_8p9p1TLF55e8ggkQGfdC32OZ7aI07Sz5.jpg)

**Comment by serapath** [comment]
**feedback `2022.10.22`**

short feedback regarding the `<` and `>` button for tabs.
I think they should not just be visible on hover, but also on active.
I would maybe even go as far to say they should always be visible.

Only tabs which open `tile.json` files will have them anyway and even amongst those, only the tile json files that actually define previous and next options will show them, so mostly they won't be visible, but when they are defined, i think it is important for the user to be aware and just showing them on hover means a user can easily miss them when they come to a workshop with many open tabs and don't hover over a specific tab, which i think is not great.

So maybe let's just make them always visible and not just on hover :-)

**Comment by Mehrabbruno** [comment]
proposed task `2022.10.24`

- [ ] Make the arrow keys CTA for navigation always visible
- [ ] In the Figma component description, worklog and/or explanatory video, mention "only files which define previous and next options will see the arrows. For others it will be disable"
* `@input` 📦 [tab_v0.0.1](https://www.figma.com/file/PiQmPX3q1V2Ph7hARR2jOm/tiling-window-manager-3?node-id=318%3A2706)
* `@output` ❓ [tab_v0.0.2]()

**Comment by Mehrabbruno** [comment]
proposed task `2022.10.24`

- [ ] Make the arrow keys CTA for navigation always visible
- [ ] In the Figma component description, worklog and/or explanatory video, mention "only files which define previous and next options will see the arrows. For others it will be disable"
* `@input` 📦 [tab_v0.0.1](https://www.figma.com/file/PiQmPX3q1V2Ph7hARR2jOm/tiling-window-manager-3?node-id=318%3A2706)
* `@output` ❓ [tab_v0.0.2]()

**Comment by serapath** [comment]
**feedback `2022.10.26`**

:+1:
