### ISSUE TITLE
Design TWM - Tab Component's Switch Program Pop-over

### ISSUE THREAD

**Issue by Mehrabbruno** [wizardamigos/wizardamigos.github.io#113]
## `@todo`

https://github.com/wizardamigos/wizardamigos.github.io/issues/111

  - [x] Design - Tab components Switch Program Pop-over
    - `@input` 📦 [WF 14: TWM specs in WF -Iteration 2- figma file`](https://www.figma.com/file/lk41O0wlkMEdPiCBGVMOO8/?node-id=897%3A11280) from #101 
    - `@input` :package: [`twm ui/ux specification`](https://hackmd.io/yrqMJjhaQm2b8MhS4Gqxhg?view) from #111 

     -  
     - [ ] Switch Programs icon `onClick` you get a pop-over containing
        - [ ] Pop-over Title
        - [ ] Pop-over Close button
        - [ ] Program container (divs which carries each Program information)
           - [ ] Program name
           - [ ] Program logo
           - [ ] Program description
        - [ ] Active state (when a program is already running it should be blue)
        - [ ] Hover state (when a program is hovered it shows a gray background)
        - [ ] Search input
    - `@output` 🏭 [`TWM iteration 15 Figma File`](https://www.figma.com/file/PiQmPX3q1V2Ph7hARR2jOm/tiling-window-manager-3?node-id=0%3A1) from [`comment`](https://github.com/wizardamigos/wizardamigos.github.io/issues/111#issuecomment-1221609607)

## `@info`

for [`TWM iteration 15 Figma File`](https://www.figma.com/file/PiQmPX3q1V2Ph7hARR2jOm/tiling-window-manager-3?node-id=0%3A1) we need to design the tab component tasks. These will be integrated into the main design file.
