### ISSUE TITLE
 Design TWM - bookmarksContainer_v0.0.1

### ISSUE THREAD

**Issue by Mehrabbruno** [wizardamigos/wizardamigos.github.io#115]
## `@todo`

#111 

  - [x] Design - bookmarksContiainer_v0.0.1
    - `@input` 📦 [WF 14: TWM specs in WF -Iteration 2- figma file`](https://www.figma.com/file/lk41O0wlkMEdPiCBGVMOO8/?node-id=897%3A11280) from #101 
    - `@input` :package: [`twm ui/ux specification`](https://hackmd.io/yrqMJjhaQm2b8MhS4Gqxhg?view) from #111 

    - 
     - [ ] Bookmark Container Component (contains)
        - [ ] Bookmarks (contains folder icon and bookmark title)
        - [ ] Collapsed bookmarks counter CTA
         - [ ] Bookmark pop-over from -> #113 
         - [ ] Collapsed Bookmark pop-over from -> #113 
        - [ ] Add to bookmark CTA

    - `@output` 🏭 [`TWM iteration 15 Figma File`](https://www.figma.com/file/PiQmPX3q1V2Ph7hARR2jOm/tiling-window-manager-3?node-id=224%3A2927) from [`comment`]()

## `@info`

for [`TWM iteration 15 Figma File`](https://www.figma.com/file/PiQmPX3q1V2Ph7hARR2jOm/tiling-window-manager-3?node-id=0%3A1) we need to design the tab containers. These will be house the tab components. read more on `twm ui/ux specification`

**Comment by Mehrabbruno** [comment]
* `done` Design - bookmarksContiainer_v0.0.1 
   * `done` Bookmark Container Component (contains) 
      * `done` Bookmarks (contains folder icon and bookmark title)
      * `done` Collapsed bookmarks counter CTA
      * `done` #122 
      * `done` #123 
      * `done` Add to bookmark CTA
      * `@output` 📦[`bookmarksContiainer_v0.0.1`](https://www.figma.com/file/PiQmPX3q1V2Ph7hARR2jOm/tiling-window-manager-3?node-id=318%3A3194)
   * `done` Record an explanatory video for Bookmarks Container 
      * `@output` 📦[`video recording`](https://github.com/wizardamigos/wizardamigos.github.io/issues/115)

**Comment by serapath** [comment]
**feedback `2022.10.14`**

1. add worklog video to previous worklog comment
2. add times behind each done task

---

bookmarks container looks otherwise good so far

**Comment by serapath** [comment]
**feedback `2022.10.14`**

1. add screencast video to worklog comment above
2. add times behind each done task

---

I think the bookmark popover is also something we have to iterate on heavily.
It will have a lot in common again with the file explorer popover.
If a bookmark is in fact a `tile.json` file, it will show the structure of tabs, but if it is a file or folder, things will look different.
Anyway, again - we should check the work done in the past, but again also the file explorer needs to be worked on first, because it will be an input for the bookmark popover :-)

**Comment by serapath** [comment]
**feedback `2022.10.22`**

saving a bookmark would not just happen via action from a tab action menu,
but also via drag'n'drop and also from any "file explorer" popover or program so a user can again also drag'n'drop from there.

Next, every bookmark tab in the bookmarks bar needs a little action menu too, because from that a user can select to open the bookmark, but also to remove (=unpin) the bookmark or maybe edit it - which gives a file explorer popover to select an alternative bookmark instead of the current one.

**Comment by Mehrabbruno** [comment]
proposed task `2022.10.24`

- [ ] Add a remove-bookmark-button on the bookmark groups/folder in the bookmarksContainer
- [ ] In the Figma component description, worklog and/or explanatory video, mention all the methods to bookmark a file or folder.
* `@input` 📦 [bookmarksContiainer_v0.0.1](https://www.figma.com/file/PiQmPX3q1V2Ph7hARR2jOm/tiling-window-manager-3?node-id=318%3A3194)
* `@output` ❓ [bookmarksContiainer_v0.0.2]()

<br><br>

feedback `2022.10.24`

> saving a bookmark would not just happen via action from a tab action menu,
but also via drag'n'drop and also from any "file explorer" popover or program so a user can again also drag'n'drop from there.

I agree with this. I think it may help some users. So, we should provide different options to bookmark. Maybe even some shortcuts.

<br><br>


> Next, every bookmark tab in the bookmarks bar needs a little action menu too, because from that a user can select to open the bookmark, but also to remove (=unpin) the bookmark or maybe edit it - which gives a file explorer popover to select an alternative bookmark instead of the current one.

I understand the requirement of an action button for the bookmarks. Maybe to use it for removing the whole group of tabs/files. Currently we do have that option in the bookmarkPopover but yeah having it outside may make it easier for users. However, I am a bit confused about the following:
* The bookmarks themselves are used as a group or a folder. User can name it whatever they wish or the same name as the folder if they choose. That named group/folder is not something present in the project directory (it could be with a different name) but rather something the user creates for themselves. It is more of a custom folder for user to keep their often visited files/folder. many folder and files from different directory can exist as siblings in this created group
* I am a bit confused about editing the bookmarks. Replacing one bookmark with another? Wouldn’t it be easier to remove a folder and add another one? Easier to code as well

**Comment by Mehrabbruno** [comment]
proposed task `2022.10.24`

- [ ] Add a remove-bookmark-button on the bookmark groups/folder in the bookmarksContainer
- [ ] In the Figma component description, worklog and/or explanatory video, mention all the methods to bookmark a file or folder.
* `@input` 📦 [bookmarksContiainer_v0.0.1](https://www.figma.com/file/PiQmPX3q1V2Ph7hARR2jOm/tiling-window-manager-3?node-id=318%3A3194)
* `@output` ❓ [bookmarksContiainer_v0.0.2]()

<br><br>

feedback `2022.10.24`

> saving a bookmark would not just happen via action from a tab action menu,
but also via drag'n'drop and also from any "file explorer" popover or program so a user can again also drag'n'drop from there.

I agree with this. I think it may help some users. So, we should provide different options to bookmark. Maybe even some shortcuts.

<br><br>


> Next, every bookmark tab in the bookmarks bar needs a little action menu too, because from that a user can select to open the bookmark, but also to remove (=unpin) the bookmark or maybe edit it - which gives a file explorer popover to select an alternative bookmark instead of the current one.

I understand the requirement of an action button for the bookmarks. Maybe to use it for removing the whole group of tabs/files. Currently we do have that option in the bookmarkPopover but yeah having it outside may make it easier for users. However, I am a bit confused about the following:
* The bookmarks themselves are used as a group or a folder. User can name it whatever they wish or the same name as the folder if they choose. That named group/folder is not something present in the project directory (it could be with a different name) but rather something the user creates for themselves. It is more of a custom folder for user to keep their often visited files/folder. many folder and files from different directory can exist as siblings in this created group
* I am a bit confused about editing the bookmarks. Replacing one bookmark with another? Wouldn’t it be easier to remove a folder and add another one? Easier to code as well

**Comment by Mehrabbruno** [comment]
[Worklog 1 `2022.10.25`](https://youtu.be/yV6FhXfWf6A)

**Comment by serapath** [comment]
**feedback `2022.10.25`**

![bookmarks popover](https://imgur.com/zc6KOLA.png)
The bookmarks popover should look like a file explorer, but when it opens, the current bookmark is highlighted (and "pinned").

THe "sub entries" shown below a pinned bookmark in the file explorer like popover:
* e.g. the sub folders of a folder,
* e.g. or a tile json file when expanded in the file explorer.

The latter type of bookmark will show potential sub tabs from different destinations when expanded in the file explorer popover, but only if a bookmark is actually bookmarking a tile json file instead of a normal file.


If you for example bookmark a folder, that folder represnets a bookmark with all that folders content, but again, the "open action" opens it in a tile with the file explorer program with that bookmarked folder opened. clicking the bookmark to show the bookmark popover shows the filex explorer popover with that pinned/bookmarked folder selected.

also the sub items of a bookmarked item can only be from different places/directories **if the bookmark under consideration is a `"tile json file"`**, which has all those files/folders from different directories specified in json in that file.

Technically, we could also consider editing such a "tile json file" on the fly inside the file explorer popover when a user selects a specific expanded entry under a tile json file and changes it ....

The bookmark in the bookmark bar still needs a few quick actions:
1. clicking the bookmark will probably just open the bookmark in a new tile
2. but clicking the little action item opens the "bookmark file explorer popover"
  * which allows to:
    1. again - open the bookmark in a new tile
    2. but also to open the bookmark in the current tile
    3. or of course edit bookmark, e.g. renaming or changing the bookmark
    4. or also unpinning/removing the bookmark

So also - no need to go to the file explorer to change or edit anything there.
The file explorer shows all the pinned items that are currently bookmarks, but so does the bookmark popover which looks like a file explorer, but with the current bookmark highlighted/selected.

Also bookmark popover or file explorer popover, both show the user what is available and the user can expand/collapse and then make decisions about pinning/unpinning or editing, etc...

**Comment by Mehrabbruno** [comment]
## A. worklog `2022.10.26`
1.

---
## B. tasks
* `in-progress` Discussion for bookmarksContainer_v0.0.2

---
## C. feedback `2022.10.26`

> the bookmarks popover should look like a file explorer, but when it opens, the current bookmark is highlighted (and "pinned")

okay sure we can keep that. in that case there is no point of bookmarkPopover we should merge or replace it with

> bookmark will show potential sub tabs from different destinations

Not sure what you mean my that tbh. Could you explain further. What you mean by potential sub tabs?

> he bookmark in the bookmark bar still needs a few quick actions

Why is there a need for this? Why don’t we just keep 1 collapsed bookmark button or a tab/card button then open fileExplorerePopover?  Even if we do it your way it should be the opposite, the explorer should open on click of the time and the action icon should show option to open the bookmarked tab, or we keep another icon to open the tab directly

>The file explorer shows all the pinned items that are currently bookmarks

Don't you this is overdoing it? Their might be cases when people create 2 different bookmarks but with the same file placed in both of them. I do that quite often when creating moodboard for designs. I think we can just keep the fileExplorer as it is and change the bookmarkPopOver to be similar to FileExplorer. only with the difference of seeing the file that the user have selected and organized

I will also suggest that we give user the power to create folder/directories within the new bookmarkPopOver So they can choose to create folders with different names suited for the files they want to store/bookmark. What do you think?


---
## D. proposals
- [ ] Discussion for bookmarksContainer_v0.0.2

**Comment by serapath** [comment]
**feedback `2022.10.26`**

> Not sure what you mean my that tbh. Could you explain further. What you mean by potential sub tabs?

you mention that bookmark popover shows different sub tabs/tiles from "different locations" in the file explorer (sorry, for saying "destinations").
So i am trying to use your words. This is happening because those are defined in a `"tile json file"` and that is a file in the file explorer and even though it is not a folder we want to be able to allow it to expand to show the sub entries (which are all the tiles and sub tiles defined in that `"tile json file"`


> Why is there a need for this? Why don’t we just keep 1 collapsed bookmark button or a 
> tab/card button then open fileExplorerePopover? Even if we do it your way it should be the 
> opposite, the explorer should open on click of the time and the action icon should show 
> option to open the bookmarked tab, or we keep another icon to open the tab directly

Fair enough.
Thought:
1. if you click to get a (action/popover) menu, that was one click
2. second click is selecting/triggering an action

So the only point i see for a "quick action" button is if it triggers with one click.
My hypothesis is, that people make bookmarks and the: **`"one click to open bookmark in a new tile"`** is what they usually want, so it is one click only on the bookmark itself.
**BUT:** editing/changing/open in same tile instead of new tile, etc... are all actions that a user also wants, so therefore we have the bookmark popover menu, where a user can choose all of those actions, but it means two clicks, to first open and then second select the action.

If we say the default one click action is not necessary, we always force users to do two clicks, then we can skip that part. what do you think?


---


> I will also suggest that we give user the power to create folder/directories
> within the new bookmarkPopOver So they can choose to create folders
> with different names suited for the files they want to store/bookmark.
> What do you think?

yes, of course.
that is already the case. of course a user can bookmark folders/directories.

> Don't you this is overdoing it?
> Their might be cases when people create 2 different bookmarks
> but with the same file placed in both of them.
> I do that quite often when creating moodboard for designs.
> I think we can just keep the fileExplorer as it is and change the bookmarkPopOver
> to be similar to FileExplorer.
> only with the difference of seeing the file that the user have selected and organized


> **"both with the same file places in both of them"**

sure, but that sounds like the bookmark is not the same file, but it is "folder A" and "folder B" bookmarked and both contain "file X", which is possible, because "file X" can be linked in both folders (A and B). That is what our file system supports.

I agree, i also do that when i do moodboards and such things.

I don't want to support the use case to have the same exact file or folder bookmarked twice in the bookmark bar directly.

Yes, you can open the same fileX or folder to tile json file twice in a tile.
But it doesn't need to appear multiple times with the same name in the bookmark bar.
But it is possible to have bookmark folderA and bookmark folderB
and each of them contains fileX. That is supported.


> I will also suggest that we give user the power to create folder/directories within the new 
> bookmarkPopOver So they can choose to create folders with different names suited for the 
> files they want to store/bookmark. What do you think?

Yes. for sure.
That is anyway the case, because that is what the file explorer popover would support anyway.
So yes. i think this should be a feature :-)
