### ISSUE TITLE
Design - `applicationPopover_v0.0.1` pop-over for tabsContainer_v0.0.1

### ISSUE THREAD

**Issue by Mehrabbruno** [wizardamigos/wizardamigos.github.io#116]
## `@todo`

https://github.com/wizardamigos/wizardamigos.github.io/issues/111

  - [x] Design - popOvers_v0.0.1
    - `@input` :package: [WF 14: TWM specs in WF -Iteration 2- figma file`](https://www.figma.com/file/lk41O0wlkMEdPiCBGVMOO8/?node-id=897%3A11280) from #101 
    - `@input` 🏭 [`twm ui/ux specification`](https://hackmd.io/yrqMJjhaQm2b8MhS4Gqxhg?view) from #111 

     -  
     - [ ] Application pop-over (toggles on onClick). it contians:
        - [ ] pop-over header (fixed to the top and contains title, total number of applications and close button)
        - [ ] Application container (contains application logo, name & desc)
        - [ ] Search input (contains search icon, inputField and close icon when added text)
     -  
    - `@output` 🏭 [`applicationPopover_v0.0.1`](https://www.figma.com/file/PiQmPX3q1V2Ph7hARR2jOm/tiling-window-manager-3?node-id=271%3A931) from [`comment`](https://github.com/wizardamigos/wizardamigos.github.io/issues/111#issuecomment-1221609607)

## `@info`

This pop-over is designed for to be placed in component [`Design TWM - Tab Component`](https://github.com/wizardamigos/wizardamigos.github.io/issues/112)

**Comment by Mehrabbruno** [comment]
[Worklog 1 `2022.09.19`](https://youtu.be/FL2PDFkHNLY)

* `done` **Design - applicationPopover_v0.0.1 (toggles on onClick). it contians: **
  * `done` pop-over header (fixed to the top and contains title, total number of applications and close button)
  * `done` Application container (contains application logo, name & desc)
  * Search input (contains search icon, inputField and close icon when added text)
  * `@output` :package: [`applicationPopover`](https://www.figma.com/file/PiQmPX3q1V2Ph7hARR2jOm/tiling-window-manager-3?node-id=318%3A2209)

**Comment by serapath** [comment]
**feedback `2022.10.14`**

great. love the component.
otherwise again:
1. missing worklog video in the worklog comment above
2. missing times behind each task that was marked as `done` :-)

**Comment by serapath** [comment]
**feedback `2022.10.22`**

The application popover needs to be able to:
1. uninstall/remove an app
2. have an indicator about available versions and which is the current, including an indicator that updates (= new versions) are available
3. needs a way to enter the link of a new application to install it to the list of available programs.

**Comment by Mehrabbruno** [comment]
How do we install application by adding a link? Can we do that on a web-application? 

<br><br>

proposed task `2022.10.24`

- [ ]  Add an action to install/uninstall Applications
- [ ]  Show the current version
- [ ]  Show the available update with version tag
- [ ]  Add option to install new applications by entering a link
* `@input` 📦 [applicationPopover_v0.0.1](https://www.figma.com/file/PiQmPX3q1V2Ph7hARR2jOm/tiling-window-manager-3?node-id=318%3A2209)
* `@output` ❓ [applicationPopover_v0.0.2]()

**Comment by serapath** [comment]
**feedback `2022.10.16`**

1. installation happens by pasting a link to the installer into the input field and pressing enter.

2. the shown version should be a dropdown or something to swtich between versions.

3. a program should be deletable (maybe requires confirmation dialog)

**Comment by Mehrabbruno** [comment]
* `done` Design - applicationPopover_v0.0.2
   * `done` remove header, and footer from the component.
   * `done` place the content inside the #125 content body
   * `@output` 📦 [`applicationPopover_v0.0.2`](https://www.figma.com/file/PiQmPX3q1V2Ph7hARR2jOm/tiling-window-manager-3?node-id=514%3A2312)
