### ISSUE TITLE
Design - `permissionPopover_v0.0.1` pop-over for `tabsContainer_v0.0.1`

### ISSUE THREAD

**Issue by Mehrabbruno** [wizardamigos/wizardamigos.github.io#117]
## `@todo`

https://github.com/wizardamigos/wizardamigos.github.io/issues/111

  - [x] Design - popOvers_v0.0.1
    - `@input` :package: [WF 14: TWM specs in WF -Iteration 2- figma file`](https://www.figma.com/file/lk41O0wlkMEdPiCBGVMOO8/?node-id=897%3A11280) from #101 
    - `@input` 🏭 [`twm ui/ux specification`](https://hackmd.io/yrqMJjhaQm2b8MhS4Gqxhg?view) from #111 

     -  
      - [ ] Permission pop-over (toggles on onClick) it contians:
        - [ ] pop-over header (fixed to the top and contains title, total number of permissions and close button)
        - [ ] Permission container (contains checkboxes with labels)
        - [ ] Search input (contains search icon, inputField and close icon when added text)
     -  
    - `@output` 🏭 [`permissionPopover_v0.0.1`](https://www.figma.com/file/PiQmPX3q1V2Ph7hARR2jOm/tiling-window-manager-3?node-id=271%3A1870) from [`comment`](https://github.com/wizardamigos/wizardamigos.github.io/issues/111#issuecomment-1221609607)

## `@info`

This pop-over is designed for to be placed in component [`Design TWM - Tab Component`](https://github.com/wizardamigos/wizardamigos.github.io/issues/112)

**Comment by Mehrabbruno** [comment]
* `done` Design - Permission pop-over (toggles on onClick) 
   * `done` permissionPopover (contains) 
      * `done` pop-over header (fixed to the top and contains title, total number of permissions and close button)
      * `done` Permission container (contains checkboxes with labels)
      * `done` Search input (contains search icon, inputField and close icon when added text)
      * `@output` 📦 [`permissionPopover_v0.0.1`](https://www.figma.com/file/PiQmPX3q1V2Ph7hARR2jOm/tiling-window-manager-3?node-id=318%3A2283)
   * `done` Record an explanatory video for permissionPopover 
      * `@output` 📦 [`video recording`](https://youtu.be/9WObRgGZl7k)

**Comment by serapath** [comment]
**feedback `2022.10.14`**

same again as always :-)
1. missing worklog video link in worklog comment above
2. missing times after each `done` task

---

regarding permission popover - we need to refine this a lot.
Basically what this is about is granting permissions to the app to read one or more files from the users file explorer, therefore the popover should probably look a lot more like the file explorer, maybe we can even re-use the file explorer component and literally allow the user to mark for each file/folder whether the app has permissions to create/read/write/delete/change? ...etc that file :-)

Or maybe the user selects files or folders and chooses permissions and then it gets added to the list of permissions to that app and file?

Or maybe for re-usability or whatever we show the file explorer anf just highlight all the files/folder where permissions are granted?

**important:** because we might need the file explorer for this section, we should maybe FIRST finish the file explorer and then use that as yet another `@input` for this component, which also means we have to refine and improve the file explorer first :-)

**Comment by Mehrabbruno** [comment]
* `done` Design - permissionPopover_v0.0.2
   * `done` remove header, and footer from the component.
   * `done` place the content inside the #125 content body
   * `@output` 📦 [`permissionPopover_v0.0.2`](https://www.figma.com/file/PiQmPX3q1V2Ph7hARR2jOm/tiling-window-manager-3?node-id=515%3A3081)
