### ISSUE TITLE
Design - `actionsPopover_v0.0.1` pop-over for `tabsContainer_v0.0.1`

### ISSUE THREAD

**Issue by Mehrabbruno** [wizardamigos/wizardamigos.github.io#118]
## `@todo`

https://github.com/wizardamigos/wizardamigos.github.io/issues/111

  - [ ] Design - Actions pop-over (toggles on onClick). it contians:
     - `@input` :package: [WF 14: TWM specs in WF -Iteration 2- figma file`](https://www.figma.com/file/lk41O0wlkMEdPiCBGVMOO8/?node-id=897%3A11280) from #101 
     - `@input` 🏭 [`twm ui/ux specification`](https://hackmd.io/yrqMJjhaQm2b8MhS4Gqxhg?view) from #111 
     - [ ] pop-over header (fixed to the top and contains title, total number of actions and close button)
     - [ ] Actions container (contains action title)
     - [ ] Search input (contains search icon, inputField and close icon when added text)
     -  
    - `@output` 🏭 [`actionsPopover_v0.0.1`](https://www.figma.com/file/PiQmPX3q1V2Ph7hARR2jOm/tiling-window-manager-3?node-id=271%3A1741) from [`comment`](https://github.com/wizardamigos/wizardamigos.github.io/issues/111#issuecomment-1221609607)

## `@info`

This pop-over is designed for to be placed in component [`Design TWM - Tab Component`](https://github.com/wizardamigos/wizardamigos.github.io/issues/112)

**Comment by Mehrabbruno** [comment]
* `done` Design - Actions pop-over (toggles on onClick). it contians: 
   * `done` actionsPopover (contains) 
      * pop-over header (fixed to the top and contains title, total number of actions and close button)
      * Actions container (contains action title)
      * Search input (contains search icon, inputField and close icon when added text)
         * `@output` 📦 [`actionsPopover_v0.0.1`](https://www.figma.com/file/PiQmPX3q1V2Ph7hARR2jOm/tiling-window-manager-3?node-id=318%3A2357)
   * `done` Record an explanatory video for actionsPopover_v0.0.1 
      * `@output` 📦 [`video recording`](https://youtu.be/hKscISIlkVM)

**Comment by serapath** [comment]
**feedback `2022.10.14`**

same again
1. needs worklog video in above worklog comment
2. needs times logged behind each task

---
otherwise, the component is great and can stay as it is :-)

**Comment by serapath** [comment]
**feedback `2022.10.22`**

one feature missing from the actions popover is that each action should have the option to display/edit the keyboard shortcust that can trigger that action while the focus is on the tab/tile of the active program. Basically keyboard shortcust here are dependent on which program tab is currently active.

**Comment by Mehrabbruno** [comment]
feedback `2022.10.24`

>each action should have the option to display/edit the keyboard shortcust

How will the editing that action work? will that edit be applied on that specific tab or all the places? Where the user can edit the shortcuts? directly from that action? If so, isn’t the click-able(action) button gonna be small? since that action button itself could be quite small.

How about we add the edit action button on that popover itself?

**Comment by serapath** [comment]
**feedback `2022.10.26`**

all actions are specific to a **program**
If action keyboard shortcuts are edited, they apply everywhere where a tab uses the same program.

I assume the keyboard shortcut could be displayed behind the action name and clicking the shortcut turns it into an input field or something for a user to press/choose different keyboard shortcut.

Keyboard shortcuts have hierarchy, so the TWM or tab which opens the program might have some keyboard shortcuts and the program cannot override those and would display a keyboard shortcut is already in use.


**if we have the clickable action button** whatever the action button does should be changable/definable form the select action popover

The only thing that can be edited is the keyboard shortcut of an action, nothing else.

**Comment by Mehrabbruno** [comment]
* `done` Design - actionsPopover_v0.0.2
   * `done` remove header, and footer from the component.
   * `done` place the content inside the #125 content body
   * `@output` 📦 [`actionsPopover_v0.0.2`](https://www.figma.com/file/PiQmPX3q1V2Ph7hARR2jOm/tiling-window-manager-3?node-id=515%3A3404)

**Comment by serapath** [comment]
**feedback `2022.10.31`**

When you open a program like figma it wont show you all the actions you can do when you open vscode.

So the action popover will read all the available action from the program that is open.
Each program that we create will provide some actions to the action popover to be displayed.

There is no way we can always show all actions that are possible with any program.

Which shortcut keys are active depends on the program tile in focus and what action it's program supports.
