### ISSUE TITLE
Design - `historyLogsPopover_v0.0.1` pop-over for `tabsContainer_v0.0.1`

### ISSUE THREAD

**Issue by Mehrabbruno** [wizardamigos/wizardamigos.github.io#119]
## `@todo`

https://github.com/wizardamigos/wizardamigos.github.io/issues/111

  - [ ] Design - History Logs pop-over (toggles on onClick). it contians:
     - `@input` :package: [WF 14: TWM specs in WF -Iteration 2- figma file`](https://www.figma.com/file/lk41O0wlkMEdPiCBGVMOO8/?node-id=897%3A11280) from #101 
     - `@input` 🏭 [`twm ui/ux specification`](https://hackmd.io/yrqMJjhaQm2b8MhS4Gqxhg?view) from #111 
     - [ ] pop-over header (fixed to the top and contains title, total number of tabs contained in history and close button)
     - [ ] History logs tab container (contains application logo, title, history/revision icon and close button)
     - [ ] Search input (contains search icon, inputField and close icon when added text)
     -  
    - `@output` 🏭 [`historyLogsPopover_v0.0.1`](https://www.figma.com/file/PiQmPX3q1V2Ph7hARR2jOm/tiling-window-manager-3?node-id=271%3A1582) from [`comment`](https://github.com/wizardamigos/wizardamigos.github.io/issues/111#issuecomment-1221609607)

## `@info`

This pop-over is designed for to be placed in component [`Design TWM - Tab Component`](https://github.com/wizardamigos/wizardamigos.github.io/issues/112)

**Comment by serapath** [comment]
**feedback `2022.10.14`**

let's start with some generic feedback
1. missing worklog video
2. missing times behind done tasks
...

---

Otherwise, I feel this popover is very similar in structure to the `collapsedTabsPopover` even though it works slightly different, so i wonder if it was possible to merge both of those components (so we finally have a merge use case) into a single component, which we can then re-use in both cases, but customizing them with different arguments when we create elements :-)

**Comment by Mehrabbruno** [comment]
* `done` Design - historyLogsPopover_v0.0.2
   * `done` remove header, and footer from the component.
   * `done` place the content inside the #125 content body
   * `@output` 📦 [`historyLogsPopover_v0.0.2`](https://www.figma.com/file/PiQmPX3q1V2Ph7hARR2jOm/tiling-window-manager-3?node-id=514%3A1545)
