### ISSUE TITLE
Design - `fileExplorePopover_v0.0.1` pop-over for `tabsContainer_v0.0.1`

### ISSUE THREAD

**Issue by Mehrabbruno** [wizardamigos/wizardamigos.github.io#120]
## `@todo`

https://github.com/wizardamigos/wizardamigos.github.io/issues/111

  - [ ] Design - File Explorer pop-over (toggles on onClick). it contians:
     - `@input` :package: [WF 14: TWM specs in WF -Iteration 2- figma file`](https://www.figma.com/file/lk41O0wlkMEdPiCBGVMOO8/?node-id=897%3A11280) from #101 
     - `@input` 🏭 [`twm ui/ux specification`](https://hackmd.io/yrqMJjhaQm2b8MhS4Gqxhg?view) from #111 
     - [ ] pop-over header (fixed to the top and contains title, total number of file/folder and close button)
      - [ ] Files container
        - [ ] Files (contains application or icon, title, and close button)
        - [ ] Folder (contains folder icon, title, toggle icon, and close button)
           - [ ] When clicked user gets a dropdown list of children File & Folders
     - [ ] Search input (contains search icon, inputField and close icon when added text)
     -  
    - `@output` 🏭 [`fileExplorePopover_v0.0.1`](https://www.figma.com/file/PiQmPX3q1V2Ph7hARR2jOm/tiling-window-manager-3?node-id=271%3A1870) from [`comment`](https://github.com/wizardamigos/wizardamigos.github.io/issues/111#issuecomment-1221609607)

## `@info`

This pop-over is designed for to be placed in component [`Design TWM - Tab Component`](https://github.com/wizardamigos/wizardamigos.github.io/issues/112)

**Comment by Mehrabbruno** [comment]
* `done`  Design - File Explorer pop-over (toggles on onClick). it contians: 
   * `done` fileExplorePopover (contains) 
      * `done` pop-over header (fixed to the top and contains title, total number of file/folder and close button)
      * `done` Files container 
         * `done` Files (contains application or icon, title, and close button)
         * `done` Folder (contains folder icon, title, toggle icon, and close button) 
            * `done` When clicked user gets a dropdown list of children File & Folders
         * `done` Search input (contains search icon, inputField and close icon when added text)
            * `@output` 📦 [`fileExplorePopover_v0.0.1`](https://www.figma.com/file/PiQmPX3q1V2Ph7hARR2jOm/tiling-window-manager-3?node-id=318%3A2104)
   * `done` Record an explanatory video for Tab Component 
      * @output` 📦 [`video recording`](https://youtu.be/EgswEKU2gUM)

**Comment by serapath** [comment]
**feeeback `2022.10.14`**

same as other issues again:
1. missing worklog video
2. missing times behind each done todo

---

FOr the first iteration, great file explorer.
Definitely something that we might need to iterate quite a lot on based on all the previous TWM work that has been done on file explorer (including files, not just folders) and how some files (e.g. tile.json files) can also be expanded similar to folders to show internal structure, etc... etc... but one thing at a time, so let's first fix all the structure, but then we need to iterate on the file explorer based on previous work :-)

**Comment by serapath** [comment]
**feedback `2022.10.22`**

So here there is so much to say, that i would say we should split the work - like in general - into:
1. fileexplorer popover (which is this issue)
2. fileexplorer component

The latter might already have an issue here on github in the old TWM1 or TWM2 issues.
There are a some older wireframes and a lot of detailed information hidden in the old wireframes. It would be good if you could try to go through them and collect all those materials, maybe check the file explorer issue (if there is one - i think there is)
And maybe also do search for words like `file explorer`, `file`, `folder`, `file tree`, `file system`, etc... on TWM1 and TWM2 issue to collect all the feedback that was already given, so we don't ahve to start all the way from scratch.

The file explorer is a very complex component, inspired by vscode file explorer but generally with lots of features :-)

Maybe we can first bring all other parts as much as possible into a good state and then deep dive into the file explorer on it's own issue to wireframe that in much more detail.

**Comment by Mehrabbruno** [comment]
feedback `2022.10.24`

>I would say we should split the work - like in general

Could you explain what you mean by this? Why is there a need for a split for this?

<br>

>an issue here on GitHub in the old TWM1 or TWM2 issue

If you could direct me to an issue or a comment specifically that would be great. There is so much text, half the time I won’t even be able to tell if I am looking at the right place or the right thing.

<br>

> Maybe we can first bring all other parts as much as possible into a good state and then deep dive into the file explorer

Okay, I will put this in-plan or on-hold.

**Comment by serapath** [comment]
**feedback `2022.10.26`**

or maybe then let's not split it yet if you don't see the need. we will see if we get to that point.

I would say, let's finish everything else first and then let's go to the file explorer when we have the the final version for the way how we work ready, so that's done and also all other TWM issues that don't require file explorer yet are done.
we can just create a list of things the file explorer should support to make the TWM work and then we go through TWM1 and TWM2 to find stuff.

I think having the TWM3 ready makes it easy for me to compare everything that was discussed in TWM1 and TWM2 to what we have to decide if we have forgotten something or not, because going through all of that i would like to do only once, because it is a lot.


**proposal:** add an input document to the file explorer issue that is suppsoed to cintain all the information from TWM1 and TWM2 about the file explorer. We can then create an extra issue for TWM1 and TWM2 summary where we produce that document and i can actually try to produce it and then we know you can't yet work perfectly well on the file explorer issue because that input document is not ready yet :-)

**Comment by Mehrabbruno** [comment]
* `done` Design - fileExplorePopover_v0.0.2
   * `done` remove header, and footer from the component.
   * `done` place the content inside the #125 content body
   * `@output` 📦 [`fileExplorePopover_v0.0.2`](https://www.figma.com/file/PiQmPX3q1V2Ph7hARR2jOm/tiling-window-manager-3?node-id=515%3A3205)
