### ISSUE TITLE
Design - `collapsedBookmarksPopover_v0.0.1` pop-over for `bookmarksContainer_v0.0.1`

### ISSUE THREAD

**Issue by Mehrabbruno** [wizardamigos/wizardamigos.github.io#123]
## `@todo`

https://github.com/wizardamigos/wizardamigos.github.io/issues/111

  - [ ] Design -  Collapsed Bookmarks pop-over (toggles on onClick). it contians:
     - `@input` :package: [WF 14: TWM specs in WF -Iteration 2- figma file`](https://www.figma.com/file/lk41O0wlkMEdPiCBGVMOO8/?node-id=897%3A11280) from #101 
     - `@input` 🏭 [`twm ui/ux specification`](https://hackmd.io/yrqMJjhaQm2b8MhS4Gqxhg?view) from #111 
     - [ ] pop-over header (fixed to the top and contains title, total number of collapsed bookmarks and close button)
     - [ ] Collapsed Bookmarks container
        - [ ] Bookmarks (contains Folder icon, title, toggle icon, and close button)
           - [ ] When clicked user gets a dropdown list of children tabs
     - [ ] Search input (contains search icon, inputField and close icon when added text)
     -  
    - `@output` 🏭 [`collapsedBookmarksPopover_v0.0.1`](https://www.figma.com/file/PiQmPX3q1V2Ph7hARR2jOm/tiling-window-manager-3?node-id=271%3A2209) from [`comment`](https://github.com/wizardamigos/wizardamigos.github.io/issues/111#issuecomment-1221609607)

## `@info`

This pop-over is designed for to be placed in component [`Design TWM - bookmarksContainer_v0.0.1`](https://github.com/wizardamigos/wizardamigos.github.io/issues/115)

**Comment by Mehrabbruno** [comment]
* `done` Design - Collapsed Bookmarks pop-over (toggles on onClick). it contians 
   * `done` collapsedBookmarksPopover (contains) 
      * `done` pop-over header (fixed to the top and contains title, total number of collapsed bookmarks and close button)
      * `done` Collapsed Bookmarks container 
         * `done` Bookmarks (contains Folder icon, title, toggle icon, and close button) 
            * `done` When clicked user gets a dropdown list of children tabs
      * `done` Search input (contains search icon, inputField and close icon when added text)
      * `@output` 📦 [`collapsedBookmarksPopover_v0.0.1`](https://www.figma.com/file/PiQmPX3q1V2Ph7hARR2jOm/tiling-window-manager-3?node-id=318%3A2603)
   * `done` Record an explanatory video for Collapsed Bookmarks Popover 
      * `@output` 📦 [`video recording`](https://youtu.be/9wJubQDoyDI)

**Comment by serapath** [comment]
**feedback `2022.10.14`**

same thing as always
1. previous worklog comment needs worklog screencast video link
2. it needs times behind each done todo

---

The collapsed bookmark component is great, it has the same issues as the non-collapsed version in that it needs to change and be more like a file explorer popover, but other than that the technique to fit it into a mobile view is great.

**Comment by serapath** [comment]
**feedback `2022.10.22`**

AS for the normal bookmarks popover, i think they should be the same.
It is a responsive component, but maybe we can design them as one component and show the different states, like collapsed and expanded or whatever you call that, so it works on mobile and desktop.
They should be merged into one component imho.

**Comment by Mehrabbruno** [comment]
* `done` Design - collapsedBookmarksPopover_v0.0.2 - `20min`
   * `done` remove header, and footer from the component.
   * `done` place the content inside the #125 content body
   * `@output` 📦 [`collapsedBookmarksPopover_v0.0.2`](https://www.figma.com/file/PiQmPX3q1V2Ph7hARR2jOm/tiling-window-manager-3?node-id=515%3A3952)

**Comment by serapath** [comment]
**feedback `2022.10.31`**

Here is my feedback regarding some unclear issues around clicking on a bookmark to open it or instead triggering the bookmark popover and selecting an entry from their and what should happen if those entries ate tile json files or sub entries of tile json files.

https://share.vidyard.com/watch/YrRKFYfptWFKFz5yT4ScGM?

Let me know if that made things more clear.
I have another previous video on the bookmarkPopover issue that also tries to explain the details.


**ALSO** If the bookmark is a folder, it opens it in a new single tile whith the file explorer program and shows the contents of that folder in that tiles.

So in that case you get a tile that looks like this (without a file tree)
![folder view](https://imgur.com/NFmJ08x.png)
And you can then maybe double click entries to "enter" a folder or open a file.
Maybe it would even display a `..` folder to go "one level up" :-)

But that is subject of the file explorer component issue i would say.
