### ISSUE TITLE
Design - ButtonComponent

### ISSUE THREAD

**Issue by Mehrabbruno** [wizardamigos/wizardamigos.github.io#127]
## `@todo` 

#112 

- [ ] Create a Button Component to place in Tab
   - [ ] add an leading icon
   - [ ] add the button text
   - [ ] make the button auto layout
   - [ ] add border-radius of 6px
   - `@output` ❓ `buttonComponent`
      - next #112
