### ISSUE TITLE
Concept : Aspects - What We Offer?

### ISSUE THREAD

**Issue by mimi-uxui-dev** [wizardamigos/wizardamigos.github.io#50]
## `@todo`
- [x] [Digital workshop]()
- [ ] Virtual Code Camp
- [ ] Skill Tree
- [ ] paid gig contract chat logs
- [ ] Wizard profile page
