### ISSUE TITLE
Profile Component

### ISSUE THREAD

**Issue by mimi-uxui-dev** [wizardamigos/wizardamigos.github.io#61]
## `@Todo`
* [ ] **Profile**
  * [ ] apply to be a maintainer
  * [ ] accept/refuse to be a maintainer
  * [ ]  accept/refuse a maintainer
  * [ ] create a gig
  * [ ] add a gig 
  * [ ] my progress in workshops
  * [ ] my progress in code camp
  * [ ] Remove email

**Comment by serapath** [comment]
**feedback `2022.03.17`**
the profile page packs a lot.

given my previous feedback, which i will try to copy/move to another comment on this issue, the profile will be something "generic" not really related to wizardamigos similar to how a crypto wallet like metamask does not belong to a specific "dapp" (decentralized app) a user interacts with.

so, next to tools like:
* create gig
* open and watch skill tree
* edit profile info (e.g. email)
* show my solved code camps
* show my solved workshops
* list my authored workshops
  * accept/reject a maintainer/contributor to it
* list my authored codecamps
  * accept/reject a maintainer/contributor to it

...there will be many more things, because as said before, the profile page is generic, so we need to find a standardized way how any other app a user wants to use using their (wizardamigos) profile (think: "sign in with facebook") ...but sign in with wizardamigos...

**how can an app "add" a section about itself to the users "profile page"?**

**how can a user manage permissions of an app on their profile page? (think: manage app permissions on facebook)**
