### ISSUE TITLE
Gigs Component

### ISSUE THREAD

**Issue by mimi-uxui-dev** [wizardamigos/wizardamigos.github.io#64]
## `@Todo`

* [ ] also on your profile page it should show you all you currently ongoing gigs so you can quickly jump back to the workshop into the view of your gig
* [ ] btw. the gig view will let you do messages of type comment (like on GitHub issues), but also some other “chat actions” (= type of messages), like: a worklog messages (where you record/upload a short screencast video) +  a feedback message + probably some other more contract related type of messages to set, review, accept, confirm, etc… work and issue payments
* [ ] Posted Gigs 
* [ ] Doing a Gig 
* [ ] Create a Gig 
* [ ] Edit a Gig 
* [ ] Delete a Gig 
* [ ] List of gigs
