### ISSUE TITLE
Tile.json Concept

### ISSUE THREAD

**Issue by mimi-uxui-dev** [wizardamigos/wizardamigos.github.io#90]
## `@todo`
* [ ] make tab button dropdown/dropup menu concept & design
  * `@input` :package: [`what have we built hackmd`](https://hackmd.io/@mimiuxui/ryTf3nkW5) from #45
  * `@input` :package: [`history content slides`](https://slides.com/taouskhoudour/palette/fullscreen#/1) from #45  
  - `@input` :package: [`brief summary slide deck`](https://slides.com/taouskhoudour/wizard-amigos) from #42
  * `@input` :package: [`concept outline description`](https://hackmd.io/@mimiuxui/rkpwZmO1q) from #46
  - [ ] brainstorm UI/UX
   
  - [ ] create slides, wireframes and markdown files
  * `@output` :question: `tile.json file slides`
    * next #89
  * `@output` :question: `tile.json file per slide in "./slides/<slidename>.md"`
    * next #89

---
