### ISSUE TITLE
Notes files, editor and viewer concept & design

### ISSUE THREAD

**Issue by mimi-uxui-dev** [wizardamigos/wizardamigos.github.io#93]
## `@todo`
* [ ] make tab button dropdown/dropup menu concept & design
  * `@input` :package: [`what have we built hackmd`](https://hackmd.io/@mimiuxui/ryTf3nkW5) from #45
  * `@input` :package: [`history content slides`](https://slides.com/taouskhoudour/palette/fullscreen#/1) from #45  
  - `@input` :package: [`brief summary slide deck`](https://slides.com/taouskhoudour/wizard-amigos) from #42
  * `@input` :package: [`concept outline description`](https://hackmd.io/@mimiuxui/rkpwZmO1q) from #46
  - [ ] brainstorm UI/UX
    - [ ] notes are stored in the users' profile, for all-time, quick and easy access.
    - [ ] notes are loaded and created from the `tile.json` file
    - [ ] i think its good a user has an empty note by default, but imagine an advanced workshop...an advanced learner might already have many notes that are relevant in that lesson context...me as a learner, i want to open all of my different notes next to the workshop to start copying and editing and updating my notes...also my user data config should remember all the notes that i loaded or linked to a workshop, so that when i go on my user profile...i can also next to each note see the list of workshops they are attached to...maybe the list of my notes on my profile page can also show me notifications which of the workshops i used a note with has updates?
    - [ ] add an empty notes file to the workshop, but when users come back the notes tool they used will be loaded again. Each workshop has one note file, this might be used to create a summary based on users input
    - [ ] in case of the Note, a user can:
        - [ ]  create a new note
        - [ ]  open a note in a markdown viewer
        - [ ]  open a note in a markdown editor
  - [ ] create slides, wireframes and markdown files
  * `@output` :question: `Notes files, editor and viewer  slides`
    * next #91 
  * `@output` :question: `Notes files, editor and viewer  per slide in "./slides/<slidename>.md"`
    * next #91 
  * `@output` :factory: `Notes files, editor and viewer  wireframes`
    * next #87

---
