### ISSUE TITLE
JSON mode concept & design

### ISSUE THREAD

**Issue by mimi-uxui-dev** [wizardamigos/wizardamigos.github.io#94]
## `@todo`
* [ ] make tab button dropdown/dropup menu concept & design
  * `@input` :package: [`what have we built hackmd`](https://hackmd.io/@mimiuxui/ryTf3nkW5) from #45
  * `@input` :package: [`history content slides`](https://slides.com/taouskhoudour/palette/fullscreen#/1) from #45  
  - `@input` :package: [`brief summary slide deck`](https://slides.com/taouskhoudour/wizard-amigos) from #42
  * `@input` :package: [`concept outline description`](https://hackmd.io/@mimiuxui/rkpwZmO1q) from #46
  - [ ] brainstorm UI/UX
    - [ ] open file/folder in a json mode
    **About Section in the Overlay:**
    - [ ] about section is a file and we need a program to open it. The information we need comes from something like a package.json file
    - [x] add about icon in the overlay, that includes
        - [x] behind the scenes 
        - [x] submit feedback
    - [ ] add to `behind the scenes` a `bug tracker` 
    - [ ] when Clicking on "Submit Feedback":
        * it opens/makes gig, a bounty is attached to it and it can be closed/removed by maintainers
        * Users who want to submit feedback see an existing similar **gig feedback**, they can add more information and extra bounty to it.
        * In maintainers chat, submitting a feedback is opening or participating with info or bounty in an existing feedback gig
  - [ ] create slides, wireframes and markdown files
  * `@output` :question: `JSON mode concept & design slides`
    * next #92 
  * `@output` :question: `JSON mode concept & design per slide in "./slides/<slidename>.md"`
    * next #92 
  * `@output` :factory: `JSON mode concept & design wireframes`
    * next #92

---
