### ISSUE TITLE
Actions list concept & design

### ISSUE THREAD

**Issue by mimi-uxui-dev** [wizardamigos/wizardamigos.github.io#96]
## `@todo`
* [ ] make tab button dropdown/dropup menu concept & design
  * `@input` :package: [`what have we built hackmd`](https://hackmd.io/@mimiuxui/ryTf3nkW5) from #45
  * `@input` :package: [`history content slides`](https://slides.com/taouskhoudour/palette/fullscreen#/1) from #45  
  - `@input` :package: [`brief summary slide deck`](https://slides.com/taouskhoudour/wizard-amigos) from #42
  * `@input` :package: [`concept outline description`](https://hackmd.io/@mimiuxui/rkpwZmO1q) from #46
  - [ ] brainstorm UI/UX
    - [ ] tab actions:
        - [ ]  click tab to select and display/focus it's content
        - [ ]  shift+click or cntr+click tab selects it but doesn't focus it
        - [ ]  double click on any tab to enter full screen zen mode
        - [ ]  no need for minimize/maximize button
    - [ ] Subscribe/unsubscribe
        - [ ] a user can subscribe to a folder
        - [ ] a user can subscribe to a file
        - [ ] a user can subscribe to then entire workshop file or everything
    - [ ] Select:
        - [ ] a user can select a tile to access Focus (Zen) Mode: in Zen Mode user can select tiles and go Zen mode where she/he can focus better, without closing the other tiles
        - [ ] a user can select more tabs from the menu or by clicking on more tabs in the tiles
        - [ ] a user can select multiple tiles to group them in `sub tile grid`
    - [ ] actions for the file/folder content: 
        - [ ] open in current tab
        - [ ] open in new tab
        - [ ] open in new tile
    - [ ] notes actions: 
        - [ ] create a new note
        - [ ] open a note in a markdown viewer
        - [ ] open a note in a markdown editor
    - [ ] tab actions: 
        - [ ] click tab to select and display/focus it's content 
        - [ ] shift+click or cntr+click tab selects it but doesn't focus it
        - [ ] double click on any tab to enter full screen zen mode
        - [ ] no need for minimize/maximize button
    - [ ] close action 
    - [ ] you can hover over an action and see hotkeys in a tooltip 
    - [ ] Tile Actions: close, minimize, maximize and open tile window dropup.  

  - [ ] create slides, wireframes and markdown files
  * `@output` :question: `Actions list concept & design slides`
    * next #95 
  * `@output` :question: `Actions list concept & design per slide in "./slides/<slidename>.md"`
    * next #95 
  * `@output` :factory: `Actions list concept & design wireframes`
    * next #95

---
