### ISSUE TITLE
Shortcuts list concept & design

### ISSUE THREAD

**Issue by mimi-uxui-dev** [wizardamigos/wizardamigos.github.io#98]
## `@todo`
* [ ] make tab button dropdown/dropup menu concept & design
  * `@input` :package: [`what have we built hackmd`](https://hackmd.io/@mimiuxui/ryTf3nkW5) from #45
  * `@input` :package: [`history content slides`](https://slides.com/taouskhoudour/palette/fullscreen#/1) from #45  
  - `@input` :package: [`brief summary slide deck`](https://slides.com/taouskhoudour/wizard-amigos) from #42
  * `@input` :package: [`concept outline description`](https://hackmd.io/@mimiuxui/rkpwZmO1q) from #46
  - [ ] brainstorm UI/UX
    - [ ] Make a shortcuts List
        - [ ] make a hackmd file for all actions with their shortcuts
            * Select : `shift click`
            * Enter Zen/Focus Mode: `Shift+z`
            * Exit Zen/Focus Mode: `Esc`
    - [ ] add shortcuts to each action and tool, when the user hovers over an icon/button it will show a tool tip with maybe a simple description about the action and tool with hotkeys
    - [ ] to re-assign shortcuts, we can do it via the `tile.json` file or in the profile
    - [ ] to present/display actions so users can find and see all of them we can put them in profile or under about, which allow users to have very convenient access to all actions quickly  
  - [ ] create slides, wireframes and markdown files
  * `@output` :question: `Shortcuts list concept & design slides`
    * next #97
  * `@output` :question: `Shortcuts list concept & design per slide in "./slides/<slidename>.md"`
    * next #97 
  * `@output` :factory: `Shortcuts list concept & design wireframes`
    * next #97

---
